fix(deps): fixed missing go cloudflare-go deps
Added cloudflare-go missing dependencies in regard to error within action run #54
Error: internal/cloudflare/cache.go:7:2: no required module provides package github.com/cloudflare/cloudflare-go; to add it: